# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200318_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='default', max_length=240),
            preserve_default=False,
        ),
    ]
