# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-18 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200318_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='publish_date',
        ),
    ]
