# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-18 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_postmodel_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='view_count',
        ),
    ]
