# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_postmodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish_datw',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
