# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200318_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_datw',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
