# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-19 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postmodel_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'blank': 'this field is not blak, please try again', 'unique': 'This title is not unique, Pease try again'}, max_length=240, unique=True, verbose_name='Title Name'),
        ),
    ]
